[package]
name = "sha_256"
version = "0.1.0"
authors = ["shernandezz <santihernandezzapata@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.5.2"